[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tcione/forest"

[workspace.dependencies]
clap = { version = "4.5.46", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9"
regex = "1"
anyhow = "1"
thiserror = "2.0.16"
tempfile = "3.8"
